### ISSUE TITLE
`isSSR` should not render as template if the request implies a non-html MIME type

### ISSUE THREAD

**Issue by lhorie** [fusionjs/fusion-core#116]
Currently, there's no good way of rendering a dynamic PDF other than doing horrible hacks.

We already do the right thing for the `.js` extension:

https://github.com/fusionjs/fusion-core/blob/fd40195010419b4e7f9f563f1e0f4fdc742b135d/src/plugins/ssr.js#L61

This logic should be extended to other MIME types, such as PDF, images, fonts, etc

**Comment by lhorie** [comment]
Related: #46

**Comment by mlmorg** [comment]
Need to come up with potential solutions.

**Comment by lhorie** [comment]
### Permutations that work today

- [x] SSR'ed url with extension with accepts header - `/home.html` - _probably doesn't matter_
- [x] SSR'ed url without extension with accepts header - `/home`
- [] SSR'ed url with extension without accepts header - `/home.html` - breaks w/ `curl`
- [] SSR'ed url without extension without accepts header - `/home` - breaks w/ `curl`
- [] Dynamic asset with extension with accepts header - `/some-dynamic-html-asset.html` - e.g. dynamic PDF for download
- [] Dynamic asset without extension with accepts header - `/some-dynamic-asset` - _probably doesn't matter_
- [x] Dynamic asset with extension without accepts header - `/some-dynamic-html-asset.html` - e.g. dynamic PDF for download
- [x] Dynamic asset without extension without accepts header - `/some-dynamic-asset` - _probably doesn't matter_
- [] Static asset with extension with accepts header - `/some-dynamic-html-asset.html`
- [] Static asset without extension with accepts header - `/some-dynamic-asset` - _probably doesn't matter_
- [x] Static asset with extension without accepts header - `/some-dynamic-html-asset.html`
- [x] Static asset without extension without accepts header - `/some-dynamic-asset` - _probably doesn't matter_
- [] Endpoint with extension with accepts header - `/api/foo.json` - currently breaks if open in new tab (e.g. for debugging)
- [] Endpoint without extension with accepts header - `/api/foo` - currently breaks if open in new tab (e.g. for debugging)
- [x] Endpoint with extension without accepts header - `/api/foo.json`
- [x] Endpoint without extension without accepts header - `/api/foo`

**pros**: it's what we have today
**cons**: doesn't work for asset downloads, and breaks common developer usage patterns

Covered cases: 8/16

### Proposed solutions so far and what scenarios they fix

#### extension regex check

`ctx.path.match(/\.(js|gif|jpg|png|pdf|html|json)$/)`

- [x] SSR'ed url with extension with accepts header - `/home.html`
- [x] SSR'ed url without extension with accepts header - `/home`
- [x] SSR'ed url with extension without accepts header - `/home.html`
- [] SSR'ed url without extension without accepts header - `/home`
- [x] Dynamic asset with extension with accepts header - `/some-dynamic-html-asset.html`
- [] Dynamic asset without extension with accepts header - `/some-dynamic-asset`
- [x] Dynamic asset with extension without accepts header - `/some-dynamic-html-asset.html`
- [x] Dynamic asset without extension without accepts header - `/some-dynamic-asset`
- [x] Static asset with extension with accepts header - `/some-dynamic-html-asset.html`
- [] Static asset without extension with accepts header - `/some-dynamic-asset`
- [x] Static asset with extension without accepts header - `/some-dynamic-html-asset.html`
- [x] Static asset without extension without accepts header - `/some-dynamic-asset`
- [x] Endpoint with extension with accepts header - `/api/foo.json`
- [] Endpoint without extension with accepts header - `/api/foo`
- [x] Endpoint with extension without accepts header - `/api/foo.json`
- [x] Endpoint without extension without accepts header - `/api/foo`

**pros**: covers all classes of use cases (ssr, dynamic asset, static asset, endpoint)
**cons**: does not address devexp of debuggging extension-less endpoints

Covered cases: 12/16

#### extension convention (no-extension = ssr, extension = non-ssr) in addition to accepts header heuristics

**pros**: same as extension regex check
**cons**: same as extension regex check 

Covered cases: 12/16

#### asset manifest check

- [x] SSR'ed url with extension with accepts header - `/home.html`
- [x] SSR'ed url without extension with accepts header - `/home`
- [] SSR'ed url with extension without accepts header - `/home.html`
- [] SSR'ed url without extension without accepts header - `/home`
- [] Dynamic asset with extension with accepts header - `/some-dynamic-html-asset.html`
- [] Dynamic asset without extension with accepts header - `/some-dynamic-asset`
- [x] Dynamic asset with extension without accepts header - `/some-dynamic-html-asset.html`
- [x] Dynamic asset without extension without accepts header - `/some-dynamic-asset`
- [x] Static asset with extension with accepts header - `/some-dynamic-html-asset.html`
- [x] Static asset without extension with accepts header - `/some-dynamic-asset`
- [x] Static asset with extension without accepts header - `/some-dynamic-html-asset.html`
- [x] Static asset without extension without accepts header - `/some-dynamic-asset`
- [] Endpoint with extension with accepts header - `/api/foo.json`
- [] Endpoint without extension with accepts header - `/api/foo`
- [x] Endpoint with extension without accepts header - `/api/foo.json`
- [x] Endpoint without extension without accepts header - `/api/foo`

**pros**: addresses any type of static assets
**cons**: does not address dynamic assets and does not address devexp of debugging endpoints

Covered cases: 10/16

#### unset ctx.element and ctx.template if ctx.body is set

**pros**: addresses all cases
**cons**: brittle (no guarantee it won't throw errors on arbitrary plugin order), hacky (least bad hook requires monkeypatching the koa getter of ctx.body), inneficient (it's still possible to run SSR code before ctx.body is set due to plugin ordering)

Covered cases: 16/16 but poorly

---

### Analysis

- Developer patterns (curl, opening an endpoint from the browser) are difficult to support
- Asset manifest is better than current strategy but does not handle dynamic endpoints
- Extension-based heuristics provide the largest amount of coverage without hacks/caveats. Unsupported cases often align with use cases that have no value.
- Heuristics based on the koa context state machine are likely to break in difficult to understand ways

---

### Recommendation

1) Use an extension-based heuristic (either a blacklist of extensions where ssr should never occur, or generically avoid ssr in any url w/ an extension) to unblock users that need dynamic endpoints.
2) Iterate on potential solutions to the difficult-to-support cases later.

**Comment by rtsao** [comment]
There's something I find really appealing about a solution using a path-prefix, e.g. route is SSR if and only if it starts with `_`. IMHO if you are not serving something to be viewed in a browser, then you should not care about the URL.

I'm less enthused about an extension-based convention, since there's more ambiguity in the case of `.html`/`.htm` extensions, which people often expect to work. Add in magic around rewrite rules and it comes even more confusing.

**Comment by slonoed** [comment]
@rtsao I think prefix doesn't conform web ideology. URL doesn't imply type, headers do. It also means that routes with `_` prefix are forbidden and application which want to use generated routes have to escape this symbol.

Example: I have an application which is more or less file browser (think about s3 file browser). And I want to show file path as URL path, like `https://example.com/any/name/path`. A path `https://example.com/_any/name/path` is broken now. To avoid this I have to replace symbol (which is super weird) or create prefix path `https://example.com/files/_any/name/path`.

Take a look at this comment https://github.com/fusionjs/fusion-core/issues/45#issuecomment-369388831, maybe it could be a better way.

**Comment by KevinGrandon** [comment]
We have implemented both parts 1) and 2) of your suggestion. I think we'll still need to iterate on this to make it nicer for entries in the asset manifest, and also potentially per-plugin setting of headers. People should generally be unblocked now, and we can continue making this better over time.
