### ISSUE TITLE
Add documentation for `from` function used in plug ins

### ISSUE THREAD

**Issue by brendean** [fusionjs/fusion-core#193]
### Type of issue

Feature request

### Description
Plug ins use the `from` to do something but I don't fully understand what and I can't find any documentation.

Some `from` usages I've seen:
https://github.com/fusionjs/fusion-core/blob/0b07bf20fed1d337507f66c83652a8fbe8751805/src/plugins/timing.js
https://github.com/fusionjs/fusion-plugin-rpc-redux-react/blob/master/src/plugin.js

### Current behavior

Can't find documentation of `from`.

### Expected behavior

Cover `from` in the "Creating a Fusion.js Plugin" documentation section.

**Comment by mlmorg** [comment]
It is sort of documented here: https://github.com/fusionjs/fusion-core#memoization

It is a convention and not an actual API so it is documented in the plugins that do have such an API.
