### ISSUE TITLE
Yarn link workflows broken

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/fusion-core#31]
When using `yarn link` on packages which leverage HTML sanitization[1] in fusion-core Symbols break across packages. 

STR:
* cd fusion-core && yarn link fusion-core
* cd fusion-plugin-react-router && yarn link fusion-plugin-react-router
* cd myapp && yarn link fusion-core && yarn link fusion-plugin-react-router
* Load your app in a browser.

Expected result:
* Page loads and everything works fine.

Actual result:
* See an error regarding escaped context HTML not appearing.

[1] https://github.com/fusionjs/fusion-core/blob/4ecade8024468c2170db0edfa131263b9a0e3c62/src/sanitization.js#L20

**Comment by rtsao** [comment]
Some things to look into:
- https://github.com/yarnpkg/yarn/issues/4206
- https://github.com/whitecolor/yalc
