### ISSUE TITLE
Flow 0.94 support

### ISSUE THREAD

**Issue by lassedamgaard** [fusionjs/fusion-core#363]
Latest version does not support flow 0.94 due to the following error. This error does not occur in 0.93
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/fusion-core/flow-typed/npm/koa_v2.x.x.js:50:10

Cannot use http$IncomingMessage [1] without 0-1 type arguments.

     node_modules/fusion-core/flow-typed/npm/koa_v2.x.x.js
       47│   declare type RequestInspect = void | RequestJSON;
       48│   declare type Request = {
       49│     app: Application,
       50│     req: http$IncomingMessage,
       51│     res: http$ServerResponse,
       52│     ctx: Context,
       53│     response: Response,

     /private/tmp/flow/flowlib_3b168199/node.js
```

Probably due to this entry in the 0.94 changelog: "Make type parameter to http$Agent covariant"

**Comment by AlexMSmithCA** [comment]
This should be resolved in the next release.  Relevant PR: https://github.com/fusionjs/fusion-core/pull/358.

Going to close this, but feel free to re-open if other issues arise with the `flow-bin` upgrade.
