### ISSUE TITLE
Investigate API for composition within DI system

### ISSUE THREAD

**Issue by ganemone** [fusionjs/fusion-core#90]
I had some ideas surrounding composition within the DI system that I wanted to get down. This is purely a brain dump and not a final interface.

A classic example of where this could be useful is the `fetch` token. We already have an example of a plugin which requires a `fetch` implementation, and provides a new `fetch` implementation - `fusion-plugin-csrf-protection`. We solved this problem through token aliasing, which works well enough but I think it can be a bit difficult to understand at first.

Lets say we had three plugins that wanted to register on the `FetchToken` (polyfill, routePrefix, csrf). Using token aliasing, we would have something like the following:

```js
const BaseFetchToken = createToken('BaseFetch');
const PrefixFetchToken = createToken('PrefixFetch');
app.register(BaseFetchToken, window.fetch);
app.register(PrefixFetchToken, RoutePrefixFetchPlugin).alias(FetchToken, BaseFetchToken);
app.register(FetchToken, CsrfPlugin).alias(FetchToken, PrefixFetchToken);
```

This is fine, but I think it would be better if we didn't have to keep track of all these different tokens. Using composition it would look like this:

```js
app.register(FetchToken, window.fetch);
app.registerCompose(FetchToken, RoutePrefixComposition);
app.registerCompose(FetchToken, CsrfComposition);
```

Now with less hand waiving...

```js
app.register(FetchToken, window.fetch);
// add routePrefix
app.registerCompose(FetchToken, (fetch) => {
  return (url, options) => {
    return fetch(window.routePrefix + url, options);
  }
});
// add csrf
app.registerCompose(FetchToken, (fetch) => {
  return createPlugin({...});
});
```

The first argument to `registerCompose` is the Token to register and compose with, and the second argument is function that takes the current resolved `provides` of the composed token, (in this case the implementation of `fetch`) and returns either a `plugin` or a new composed value directly. In the case of returning a `plugin`, the value that will be composed will be the result of the plugin's `provides` function.

Thoughts?

**Comment by lhorie** [comment]
The main issue I see is that this isn't so much composition as it is a state machine that re-introduces registration order dependence, so for example, if we wanted to refactor a scaffold into fusion-opinions.js and app-space-plugins.js, things might break in the same way they could break in the pre-DI world

**Comment by ganemone** [comment]
> The main issue I see is that this isn't so much composition as it is a state machine that re-introduces registration order dependence

I don't think it should introduce order dependence, since none of your compositions should rely on previous or future compositions. They all only rely on the initial implementation, which is the thing that is not registered as a composition. For example, in the `fetch` example above, you can reorder your registrations in any way you want and it will work as expected.

**Comment by AlexMSmithCA** [comment]
I like this idea and think that it works well for the `fetch` case above.  Although it does feel like a subset of what the `.alias` approach can support.  For example, how might I use composition to solve the use case of wanting to supply _different_ implementations to different plugins.

For example, I may have two loggers that are functionally the same (i.e. both log things) but one is used for incredibly fast, streaming logs that get periodically purged and the other expects a slower stream of logs to a persistent data store.  In that case I may want to provide the different loggers to plugins depending upon what types of logs I'm expecting.

It doesn't feel like the composition approach would work here, whereas the aliasing might.  Am I interpreting that correctly?

**Comment by ganemone** [comment]
@AlexMSmithCA good point - we potentially still need to support aliasing. However, I think that use case is likely less common

**Comment by KevinGrandon** [comment]
Talked with Giancarlo a bit and we're currently looking as two distinct APIs to handle this.

```
app.enhance(FetchToken, SomeFetchThing)
app.enhance(EnhancerToken, (enhancer) => {
  return compose(enhancer, reactorEnhancer);
});

app.compose(EnhancerToken, ReactorEnhancerPlugin);
app.compose(EnhancerToken, ReduxActionEmitterEnhancerPlugin);
app.compose(EnhancerToken, EnhancerFunction);
```

**Comment by lhorie** [comment]
Another case that we discussed offline was where a plugin would need a `fetch` that didn't do csrf/route prefix things (e.g. for CORS requests). A possible workaround would be to make the csrf and route prefix plugins gracefully handle CORS, but one can see that this approach might not scale well as the number of permutations increases.

**Comment by lhorie** [comment]
As a separate idea, we could probably decouple composition. This would at least allow us to tree-shake `compose` if it's not needed.

```js
import {compose} from 'fusion-core';

app.register(EnhancerToken, compose(ReactorEnhancerPlugin, ReduxActionEmitterEnhancerPlugin, EnhancerFunction));
```
